# Generated by Django 4.2.1 on 2023-05-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50, verbose_name='Местоположение')),
                ('location_background', models.ImageField(upload_to='backgrounds/')),
            ],
            options={
                'verbose_name_plural': 'Местоположения',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField()),
                ('dislike', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.location')),
            ],
            options={
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
