# Generated by Django 4.2.1 on 2023-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_background',
        ),
        migrations.AddField(
            model_name='location',
            name='dislike_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='like_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='main_image',
            field=models.ImageField(null=True, upload_to='location_images/'),
        ),
    ]
