# Generated by Django 4.2.1 on 2023-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_header',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
