# Generated by Django 4.2.1 on 2023-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_alter_location_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_link',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Ссылка на страницу'),
        ),
    ]
