# Generated by Django 4.2.1 on 2023-05-22 11:08

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_location_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='header_color',
            field=colorful.fields.RGBColorField(null=True, verbose_name='Цвет текста'),
        ),
    ]
